//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoriler
    {
        public int FavoriId { get; set; }
        public Nullable<int> FavoriKitapId { get; set; }
        public Nullable<int> FavoriKullaniciId { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
    }
}
