//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.Emanetler = new HashSet<Emanetler>();
            this.Favoriler = new HashSet<Favoriler>();
        }
    
        public int KitapId { get; set; }
        public string KitapAd { get; set; }
        public Nullable<int> KitapYazar { get; set; }
        public Nullable<int> KitapTur { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> BaskiSayisi { get; set; }
        public string KitapOzet { get; set; }
        public Nullable<int> KitapAdeti { get; set; }
        public string KitapFotoUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emanetler> Emanetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoriler> Favoriler { get; set; }
        public virtual Turler Turler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
